---
# tasks file for ansible-droidcam
- name: Get and Unarchive Executable
  ansible.builtin.unarchive:
    src: https://files.dev47apps.net/linux/droidcam_latest.zip
    dest: /opt/droidcam
    remote_src: yes

- name: Execute the command in remote shell; stdout goes to the specified file on the remote
  ansible.builtin.shell: /opt/droidcam/install-client

