---
# tasks file for ansible-droidcam
- name: Create droidcam folder
  ansible.builtin.file:
    path: /opt/droidcam
    state: directory
    mode: '0755'

- name: Get and Unarchive Executable
  ansible.builtin.unarchive:
    src: https://files.dev47apps.net/linux/droidcam_latest.zip
    dest: /opt/droidcam
    remote_src: yes

- name: Execute installer
  shell: "/opt/droidcam/install-client"
  args:
    chdir: /opt/droidcam/

- name: Execute V4L2 Loopback installer via DKMS
  shell: "/opt/droidcam/install-dkms"
  args:
    chdir: /opt/droidcam/
